/**
 *  @file   SimulationAnalysis.h
 *  @brief  Simulation output analysis and plot generation
 *  @author Afroditi Toufa
 *  @date   2020-07-09
 ***********************************************/



#ifndef SIMULATIONANALYSIS_H
#define SIMULATIONANALYSIS_H

#include <QDialog>
#include <QProcess>


namespace Ui {
class SimulationAnalysis;
}

class SimulationAnalysis : public QDialog
{
    Q_OBJECT

public:
    /**
     * @brief class constructor
     * @param QWidget parent
     * @param Simulation output .dat file
     */
    explicit SimulationAnalysis(QWidget *parent = nullptr,QString str="");
    ~SimulationAnalysis();
    /**
     * @brief String that holds the simulation's output filename
     */
    QString DatFile;



signals:
void closeAll();

public slots:
   /**
    * @brief  Reads the text output that is generated by the python script
    */
   void Print(const QString&);
   /**
    * @brief Runs the dsbCount_Upgraded.py analysis script in a separate process with input the output .dat file
    * of the simulation. Opens the generated plots
    */
   void runAnalysis();
   /**
    * @brief Open and edit the dsbCount_Upgraded.py analysis script
    */
   void open_script();
   /**
    * @brief Sets the completion of the dsbCount_Upgraded.py script process and prints the generated text output.
    * @param exit code return by the process
    * @param set the process status whether it is completed successfully or returns an error code.
    */
   void itHasFinished(int exitCode, QProcess::ExitStatus exitStatus);

private slots:
   /**
    * @brief Closes the current and every other open dialog of the program
    */
   void on_PB_finish_pressed();

private:
    Ui::SimulationAnalysis *ui;
};

#endif // SIMULATIONANALYSIS_H
